GET http://test-project.localhost/api/get_event?user_id=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6InVzZXIyIiwiZW1haWwiOiJ1c2VyMkBnbWFpbC5jb20iLCJleHAiOjE3NDc5MTEwNDl9.CX8XWJVaK8pCEVqUl_WvzHHavkZhrSNpGzo47nWe9Sg
Cookie: CSRF-TOKEN=71f3f86a95b7ad2360fb70e8fb18f3ccd11faaaf149014b23bdd373e356f961c; PHPSESSID=pbp6noum63bj6su8u7mok0t5cn
